---
#
# Installing Kibana
#

# Install Kibana 

- name: Install Kibana with apt
  apt:
   name: kibana
   update_cache: yes
 
# Configurations

- name: Updating the config file to allow outside access
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'server.host:'
   line: 'server.host: 0.0.0.0'

- name: Defining server port
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'server.port:'
   line: 'server.port: 5601'
    
- name: Defining Elasticsearch URL
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'elasticsearch.url:'
   line: 'elasticsearch.url: "http://localhost:9200"'

# Install X-Pack

- name: Install X-Pack
  command: /usr/share/elasticsearch/bin/kibana-plugin install x-pack

# Define Elasticsearch username and password.

- name: Defining Kibana User
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'elasticsearch.username'
   line: 'elasticsearch.url: "kibana'

- name: Defining Kibana Password
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'elasticsearch.password'
   line: 'elasticsearch.password:'

# Starting Kibana

- name: Starting Kibana
  service:
   name: kibana
   state: started
